---
title: "GazeCon Pilot"
author: "Felicia Zhang"
date: '2016-12-12'
output: html_document
---

Import data
```{r}
library(ggplot2) 
library(zoo)
library(reshape)
library(plyr)
library(scales) 
library(data.table)
library(signal)
library(matrixStats)
library(lme4)
library(arm)

raw.data1 =  read.csv("/Volumes/emberson/ResearchProjects/Pupillometry/GazeConV2/Data/Experiment2/GazeConV2_sub1-6.csv")
raw.data2 =  read.csv("/Volumes/emberson/ResearchProjects/Pupillometry/GazeConV2/Data/Experiment2/GazeConV2_sub7-8.csv")
raw.data3 =  read.csv("/Volumes/emberson/ResearchProjects/Pupillometry/GazeConV2/Data/Experiment2/GazeConV2_sub10-17.csv")
raw.data4 =  read.csv("/Volumes/emberson/ResearchProjects/Pupillometry/GazeConV2/Data/Experiment2/GazeConV2_sub18-22.csv")
raw.data5 =  read.csv("/Volumes/emberson/ResearchProjects/Pupillometry/GazeConV2/Data/Experiment2/GazeConV2_sub24-29.csv")
raw.data6 =  read.csv("/Volumes/emberson/ResearchProjects/Pupillometry/GazeConV2/Data/Experiment2/GazeConV2_sub30-32.csv")
raw.data7 =  read.csv("/Volumes/emberson/ResearchProjects/Pupillometry/GazeConV2/Data/Experiment2/GazeConV2_sub33-35.csv")

orig <- rbind(raw.data1,raw.data2,raw.data3,raw.data4,raw.data5,raw.data6,raw.data7)

```


```{r}
#1. Make a copy of original and some class conversions
poo <- orig
poo$RIGHT_PUPIL_SIZE <- as.numeric(as.character(poo$RIGHT_PUPIL_SIZE))
poo$RIGHT_GAZE_X <- as.numeric(as.character(poo$RIGHT_GAZE_X))
poo$RIGHT_GAZE_Y <- as.numeric(as.character(poo$RIGHT_GAZE_Y))

#the warnings appear bc of converting . to NA, which is correct
length(which(orig$RIGHT_PUPIL_SIZE=="."))
length(which(is.na(poo$RIGHT_PUPIL_SIZE)))

#2. Assigning each subject a number for subID so it's easier to index 
poo$subID <- 0
subs <- unique(poo$RECORDING_SESSION_LABEL)
for (i in 1:length(subs)){
  poo$subID[poo$RECORDING_SESSION_LABEL == subs[i]] <- i  
}

unique(poo$subID)

#3. Standardize time 
subs <- unique(poo$subID)
for (j in 1:length(subs)) {
  trials <- unique(poo$TRIAL_INDEX[poo$subID==j])
  print(j)
  for (i in 1:length(trials)) {
    times = poo$TIMESTAMP[poo$subID == subs[j] & poo$TRIAL_INDEX == trials[i]] #gets the timestamp for a trial for a subject
    start = min(times) #finds the smallest timestamp
    poo$TIMECODE[poo$subID == subs[j] & poo$TRIAL_INDEX == trials[i]] = poo$TIMESTAMP[poo$subID == subs[j] & poo$TRIAL_INDEX == trials[i]] - start
  }}

#4. Check hertz recorded at 
for (i in 1:length(unique(poo$subID))) {
  blah <- subset(poo, subID == i)
  print(i)
  print(head(blah$TIMECODE))
}

#5. downsample to 250 Hz (every 4 ms)
#create vector 2 - 8764 going up by 4
i <- max(poo$TIMECODE)
ii <- seq(2, i, by=4 )

poo <- poo[ !poo$TIMECODE %in% ii, ]
#double check
for (i in 1:length(unique(poo$subID))) {
  blah <- subset(poo, subID == i)
  print(i)
  print(head(blah$TIMECODE))
}

#6. Convert pupil area to diameter for certain participants 
# diameter = 256 * sqrt(area / Pi)
diameter <- function (x) {
  256*sqrt(x/pi)
}

subs <- unique(poo$subID)
for (i in 1:length(subs)){
  summary(poo$RIGHT_PUPIL_SIZE[poo$subID==subs[i]])
  a <- summary(poo$RIGHT_PUPIL_SIZE[poo$subID==subs[i]])
  if (a[4] < 1000){ #meaning it's recorded in area
    start <- min(which(poo$subID==subs[i])) #find start of that participant
    end <- max(which(poo$subID==subs[i])) #find end of that participant
    poo$RIGHT_PUPIL_SIZE[start:end] <- sapply(poo$RIGHT_PUPIL_SIZE[start:end],diameter) 
  }}

summary(poo$RIGHT_PUPIL_SIZE)

#7a. Remove samples that are off the computer screen
#1280 (X) x 1024 (Y) 
poo <- subset(poo, RIGHT_GAZE_Y < 1025)
poo <- subset(poo, RIGHT_GAZE_X < 1281)
poo <- subset(poo, RIGHT_GAZE_X > -0.1)

#7b. Fill in blinks (up to 85 samples)
#blinks were identified using Eyelink
#The duration of a blink is on average 100-150 milliseconds according to UCL researcher (conservative)
#between 100-400ms according to the Harvard Database of Useful Biological Numbers (liberal)

poo <- data.table(poo) #converts data.frame to data.table, faster to manipulate with large data
poo <- poo[, orig := .I] #creates column called 'orig' with row index

yoo <- data.frame(RECORDING_SESSION_LABEL= character(), HTARGET_DISTANCE= numeric(), HTARGET_X= numeric(),HTARGET_Y= numeric(),LEFT_GAZE_X= numeric(),LEFT_GAZE_Y= numeric(),LEFT_PUPIL_SIZE= numeric(),LEFT_IN_BLINK= numeric(), RIGHT_GAZE_X= numeric(),RIGHT_GAZE_Y= numeric(),RIGHT_IN_BLINK= numeric(), RIGHT_PUPIL_SIZE= numeric(),SAMPLE_INDEX= numeric(),SAMPLE_MESSAGE= character(),TIMESTAMP= numeric(),TRIAL_INDEX= numeric(),astim1= numeric(),astim2= numeric(),condition= numeric(),dotcolor1=numeric(),dotcolor2=numeric(),dotcolor3=numeric(),trialtype= numeric(),vstim1= numeric(),vstim2= numeric(),subID= numeric(),TIMECODE= numeric(),orig= numeric(),rleLength= numeric())

for (i in 1:length(subs)) { #for each subject
  poo2 <- subset(poo, subID==i)
  poo2 <- poo2[, rleLength := {rr <- rle(is.na(poo2$RIGHT_PUPIL_SIZE)); rep(rr$length, rr$length)}]
  #create column rleLength that counts consecutive filled or NA values (figure out how long NA values are)
  yoo <- rbind(yoo,poo2)
}

poo <- yoo

#Only fill in NA gaps with length < 100 (100 samples = 400ms) going liberal
poo$RIGHT_PUPIL_SIZE <- with(poo, ifelse(rleLength < 400, na.approx(RIGHT_PUPIL_SIZE), RIGHT_PUPIL_SIZE))
summary(poo$RIGHT_PUPIL_SIZE) #hopefully very little NA's

#8. relabel beginning baseline as trial 0
poo$SAMPLE_MESSAGE <- as.character(poo$SAMPLE_MESSAGE)
subs <- unique(poo$subID)
for (j in 1:length(subs)) {
  trials <- unique(poo$TRIAL_INDEX[poo$subID==subs[j]])
  y <- min(which(poo$subID==subs[j]))
  yy <- which(poo$SAMPLE_MESSAGE[poo$subID==subs[j]]=="BaselineEnd")
  if (length(yy)==0) {
    yy <- 0
    print(c(j,"no trial 0"))
  } else {
    yyy <- y+yy-1
    poo$TRIAL_INDEX[y:yyy] <- 0
    print(j)
  }}
#some subjects don't have baselineend message for trial 1 (2,3,12,22,23,25,27,28,30) after we removed samples

#so let's get the average time of when it's usually sent, and add it in for every subject
meanbaselineend <- mean(poo$TIMECODE[poo$SAMPLE_MESSAGE=="BaselineEnd"])
meanbaselineend2 <- 3168

z <- c(1,2,3,4,5,6,8,9,10,11,12,17:30) #subjects that don't have trial 1
for (j in 1:length(z)) {
  poo$TRIAL_INDEX[poo$TRIAL_INDEX==1 & poo$subID==z[j] & poo$TIMECODE < 3170] <- 0
}

#9. Correct timecode for trial 1
subs <- unique(poo$subID)
for (j in 1:length(subs)) {
  mi <- min(poo$TIMECODE[poo$TRIAL_INDEX==1 & poo$subID==subs[j]])
  poo$TIMECODE[poo$TRIAL_INDEX==1 & poo$subID==subs[j]] <- poo$TIMECODE[poo$TRIAL_INDEX==1 & poo$subID==subs[j]] - mi
}

#10. Calculate percentage change from baseline
pooC <- poo
subs <- unique(pooC$subID)
pooC$PUPIL_CORRECTED <- 99

for (j in 1:length(subs)) {
  trials <- unique(pooC$TRIAL_INDEX[pooC$subID==subs[j]])
  print(j)
  for (i in 2:length(trials)) {
      #get 500ms baseline from trial before it (that's why i-1)
      end <- max(which(pooC$TRIAL_INDEX==trials[i-1] & pooC$subID == subs[j]))
      start <- end-124
      baseline <- pooC$RIGHT_PUPIL_SIZE[start:end] #gets all the pupil size during that period
      baselineavg <- mean(baseline, na.rm = TRUE) #baseline avg
      pooC$PUPIL_CORRECTED[pooC$TRIAL_INDEX == trials[i] & pooC$subID == subs[j]] <- (pooC$RIGHT_PUPIL_SIZE[pooC$TRIAL_INDEX == trials[i] &pooC$subID == subs[j]] - baselineavg) / baselineavg
    }}

#remove trials that didn't have a baseline calculated
poo <- subset(pooC, PUPIL_CORRECTED < 99)

```

Filtering
```{r}
#1. Remove outliers - samples more than 2.5 SDs from the mean pupil size within a trial were removed
subs <- unique(poo$subID)
poo$outlier <- 0
for (j in 1:length(subs)) {
  trials <- unique(poo$TRIAL_INDEX[poo$subID==subs[j]])
  print(j)
  for (i in 1:length(trials)) {
    # calculate mean of pupil for one trial of one subject
    avg <- mean(poo$RIGHT_PUPIL_SIZE[poo$TRIAL_INDEX==trials[i] & poo$subID==subs[j]],na.rm = TRUE)
    # calculate 2.5 SD 
    stdev <- sd(poo$RIGHT_PUPIL_SIZE[poo$TRIAL_INDEX==trials[i] & poo$subID==subs[j]],na.rm = TRUE) # one SD
    up.stdev <- avg+(stdev*2.5) #upperbound
    low.stdev <- avg-(stdev*2.5) #lowerbound
    # relabel the ones outside 2.5 SD as 99
    poo$outlier[poo$TRIAL_INDEX==trials[i] & poo$subID==subs[j] & poo$RIGHT_PUPIL_SIZE > up.stdev] <- 99
    poo$outlier[poo$TRIAL_INDEX==trials[i] & poo$subID==subs[j] & poo$RIGHT_PUPIL_SIZE < low.stdev] <- 99
  }}

#2. Remove trials: more than 50% were bad
subs <- unique(poo$subID)
poo$trial.p.missing <- 999
for (j in 1:length(subs)) {
  trials <- unique(poo$TRIAL_INDEX[poo$subID==subs[j]])
  print(j)
  for (i in 1:length(trials)) {
    p.missing <- length(which(is.na(poo$RIGHT_PUPIL_SIZE[poo$TRIAL_INDEX==trials[i] & poo$subID==subs[j]])))/length(poo$RIGHT_PUPIL_SIZE[poo$TRIAL_INDEX==trials[i] & poo$subID==subs[j]])*100
    b <- min(which(poo$TRIAL_INDEX==trials[i] & poo$subID==subs[j]))
    bb <- max(which(poo$TRIAL_INDEX==trials[i] & poo$subID==subs[j]))
    poo$trial.p.missing[b:bb] <- p.missing
  }}

#3. Remove subjects: more than 50% of data were bad
subs <- unique(poo$subID)
poo$percentmissing.sub <- 999
for (j in 1:length(subs)) {
  p.missing <- length(which(is.na(poo$RIGHT_PUPIL_SIZE[poo$subID==subs[j]])))/length(poo$RIGHT_PUPIL_SIZE[poo$subID==subs[j]])*100
  b <- min(which(poo$subID==subs[j]))
  bb <- max(which(poo$subID==subs[j]))
  poo$percentmissing.sub[b:bb] <- p.missing
  print(j)
}

poo <- subset(poo, TRIAL_INDEX > 0) #remove trial 0
poo2 <- subset(poo, outlier == 0) #remove bad samples 
poo3 <- subset(poo2, trial.p.missing < 50) #keep trials with less than 50% bad
poo4 <- subset(poo3, percentmissing.sub < 50) #keep subjects with less than 50% bads
```

subject graphs
```{r}
#number of trials per subject before preprocessing
#condition 1= AV, 2 = VA
foo <- ddply(poo,.(subID,condition),summarise,numoftrials=length(unique(TRIAL_INDEX))) 

ggplot(foo,aes(x=factor(subID),y=numoftrials,color=factor(condition),fill=factor(condition)))+
  theme_bw()+theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line = element_line(colour = "black"))+
  geom_bar(stat="identity")+ggtitle("Number of trials completed (before preprocessing)")+
  labs(x = "Subject ID", y = "Number of trials")+
  theme(plot.title = element_text(face="bold", size=20, hjust=0))+
  theme(axis.title = element_text(face="bold", size=20))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  scale_y_continuous(limits=c(0,24),breaks=seq(0,24,2))+
  scale_fill_discrete(name="Block",breaks=c("1","2"),labels=c("AV", "VA"))+guides(color=FALSE)

foo <- ddply(poo4,.(subID,condition),summarise,numoftrials=length(unique(TRIAL_INDEX))) 

#after preprocessing
ggplot(foo,aes(x=factor(subID),y=numoftrials,color=factor(condition),fill=factor(condition)))+
  theme_bw()+theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line = element_line(colour = "black"))+
  geom_bar(stat="identity")+ggtitle("Number of trials completed (after preprocessing)")+
  labs(x = "Subject ID", y = "Number of trials")+
  theme(plot.title = element_text(face="bold", size=20, hjust=0))+
  theme(axis.title = element_text(face="bold", size=20))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  scale_y_continuous(limits=c(0,24),breaks=seq(0,24,2))+
  scale_fill_discrete(name="Block",breaks=c("1","2"),labels=c("AV", "VA"))+guides(color=FALSE)

#percent looking per subject after preprocessing
ggplot(poo4,aes(x=factor(subID),y=100-percentmissing.sub))+
  theme_bw()+theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line = element_line(colour = "black"))+
  geom_bar(stat="identity")+ggtitle("Percent looking (after preprocessing)")+
  labs(x = "Subject ID", y = "Percent looking")+
  theme(plot.title = element_text(face="bold", size=20, hjust=0))+
  theme(axis.title = element_text(face="bold", size=20))+ 
  theme(axis.text.x  = element_text(size=14),axis.text.y  = element_text(size=14))+
  theme(legend.text=element_text(size=14),legend.title=element_text(size=14))+
  scale_y_continuous(limits=c(0,100),breaks=seq(0,100,20))

```

```{r}
write.csv(poo, "GazeConV2_preprocessed_all.csv", row.names=TRUE) #save to computer
write.csv(poo4, "GazeConV2_preprocessed_final.csv", row.names=TRUE) #save to computer

saveRDS(poo, "GazeConV2_rawdata.rds")
saveRDS(poo, "GazeConV2_preprocessed_all.rds")
saveRDS(poo4, "GazeConV2_preprocessed_final.rds")
```
